### ISSUE TITLE
"File not found"

### ISSUE THREAD

**Issue by uracs** [pekkah/Tanka.FileSystem.WebApi#3]
Hi!

When I tried to upload an image file I got an exception "File Not Found".

    FlowRequest request = await _requestReader.ReadGetAsync(context.HttpRequest);

            if (!IsValidRequest(context, request))
            {
                return context.HttpRequest.CreateErrorResponse(
                    HttpStatusCode.BadRequest,
                    "Invalid flow GET request");
            }

            string filePath = GetChunkFilePath(context, request);

            if (!await _fileSystem.ExistsAsync(filePath))
            {
                return context.HttpRequest.CreateErrorResponse(
                    HttpStatusCode.NotFound,
                    "File not found");
            }

            return context.HttpRequest.CreateResponse(HttpStatusCode.OK);
        }

The application is looking for a folder which is not exist.

"Images/chunks/84931-a1641090906bef9bjpg/00000001_84931-a1641090906bef9bjpg.chunk"

How can I resolve this problem? 

Thanks advanced!

uracs

**Comment by pekkah** [comment]
At what point to you get this error? The GET request is designed to return 404 when the file does not exists. This is how Flow.JS knows which parts of the file are already uploaded.

**Comment by uracs** [comment]
I get error here:
if (!await _fileSystem.ExistsAsync(filePath))

Is it a normal behavior? Sorry, maybe I misunderstood you.

I can see the image link in the list on the application page, but when I click on the link the browser cannot show the image because it cannot find. It is also a 404 error.

I guess I did not catch something. I try to use this example to upload an image using angularjs.
Where can I see the downloaded image?

**Comment by pekkah** [comment]
The sample is by default configured to upload files to App_Data folder.

FilesController.cs
```
public FilesController()
{
  _fileSystem = new FileSystem
  {
        GetFilePathFunc = filePath => string.Format(
                    "{0}/{1}",
                    HostingEnvironment.MapPath("~/App_Data").Replace("\\", "/"),
                    filePath)
  };

  _flow = new Flow(_fileSystem);
}
```

Urls for the sample are configured set so that uploads both GET, POST actions of Flow.JS use the `/uploads/{folderName}` routes and downloading should hit the GetFile method of the FilesController by url `/{*filePath}`.

Have you done any changes to the sample?

**Comment by pekkah** [comment]
@uracs did you solve your issue?

**Comment by JT-Bruch** [comment]
I ran your sample - after getting the same error as @uracs with my implementation and I am getting that error in both the sample and my implementation.

It appears that the HttpRequest.Method is being set to GET for both the Get & Post methods which is causing issues.

When I comment out 

    if (context.HttpRequest.Method == HttpMethod.Get)
    {
         return await HandleGetRequest(context);
    }

the drag and drop/single file work, but none of the rest do.
